### ISSUE TITLE
Code For Windows and the paper related to that

### ISSUE THREAD

**Issue by golenoosh** [jacirrone/OutPredict#1]
Hi,
Thanks for the code.
I downloaded the code, but i cannot get the output. Is is because the code is executable only on Mac and Linux? 
And also I am new in this field and I recently started working with Professor Shasha. Can you provide me a related paper, so i can understand the concept and the data properly?

Golnoush
Thanks

**Comment by hpink97** [comment]
@golenoosh , did you manage to solve this issue? I am also attempting to run this code in windows and I am having issues getting OpenMP to work. I am also wondering if this code is only executable in Linux or Mac.
